# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

coordinate_rotate <- function(coords, theta) {
    .Call("GWmodel_coordinate_rotate", PACKAGE = 'GWmodel', coords, theta)
}

eu_dist_mat <- function(in_locs, out_locs) {
    .Call("GWmodel_eu_dist_mat", PACKAGE = 'GWmodel', in_locs, out_locs)
}

eu_dist_smat <- function(in_locs) {
    .Call('GWmodel_eu_dist_smat', PACKAGE = 'GWmodel', in_locs)
}

eu_dist_vec <- function(in_locs, out_loc) {
    .Call("GWmodel_eu_dist_vec", PACKAGE = 'GWmodel', in_locs, out_loc)
}

mk_dist_mat <- function(in_locs, out_locs, p) {
    .Call('GWmodel_mk_dist_mat', PACKAGE = 'GWmodel', in_locs, out_locs, p)
}

mk_dist_smat <- function(in_locs, p) {
    .Call('GWmodel_mk_dist_smat', PACKAGE = 'GWmodel', in_locs, p)
}

mk_dist_vec <- function(in_locs, out_loc, p) {
    .Call('GWmodel_mk_dist_vec', PACKAGE = 'GWmodel', in_locs, out_loc, p)
}

cd_dist_mat <- function(in_locs, out_locs) {
    .Call('GWmodel_cd_dist_mat', PACKAGE = 'GWmodel', in_locs, out_locs)
}

cd_dist_smat <- function(in_locs) {
    .Call('GWmodel_cd_dist_smat', PACKAGE = 'GWmodel', in_locs)
}

cd_dist_vec <- function(in_locs, out_loc) {
    .Call('GWmodel_cd_dist_vec', PACKAGE = 'GWmodel', in_locs, out_loc)
}


md_dist_mat <- function(in_locs, out_locs) {
    .Call('GWmodel_md_dist_mat', PACKAGE = 'GWmodel', in_locs, out_locs)
}

md_dist_smat <- function(in_locs) {
    .Call('GWmodel_md_dist_smat', PACKAGE = 'GWmodel', in_locs)
}

md_dist_vec <- function(in_locs, out_loc) {
    .Call('GWmodel_md_dist_vec', PACKAGE = 'GWmodel', in_locs, out_loc)
}

bisq_wt_vec <- function(distv, bw) {
    .Call('GWmodel_bisq_wt_vec', PACKAGE = 'GWmodel', distv, bw)
}

bisq_wt_mat <- function(distm, bw) {
    .Call('GWmodel_bisq_wt_mat', PACKAGE = 'GWmodel', distm, bw)
}

gauss_wt_vec <- function(distv, bw) {
    .Call('GWmodel_gauss_wt_vec', PACKAGE = 'GWmodel', distv, bw)
}

gauss_wt_mat <- function(distm, bw) {
    .Call('GWmodel_gauss_wt_mat', PACKAGE = 'GWmodel', distm, bw)
}

tri_wt_vec <- function(distv, bw) {
    .Call('GWmodel_tri_wt_vec', PACKAGE = 'GWmodel', distv, bw)
}

tri_wt_mat <- function(distm, bw) {
    .Call('GWmodel_tri_wt_mat', PACKAGE = 'GWmodel', distm, bw)
}

exp_wt_vec <- function(distv, bw) {
    .Call('GWmodel_exp_wt_vec', PACKAGE = 'GWmodel', distv, bw)
}

exp_wt_mat <- function(distm, bw) {
    .Call('GWmodel_exp_wt_mat', PACKAGE = 'GWmodel', distm, bw)
}

gw_reg <- function(x, y, w, hatmatrix,focus) {
    .Call('GWmodel_gw_reg', PACKAGE = 'GWmodel', x, y, w, hatmatrix,focus)
}

gw.fitted <- function(X, beta) {
    .Call('GWmodel_fitted', PACKAGE = 'GWmodel', X, beta)
}

ehat <- function(y, X, beta) {
    .Call('GWmodel_ehat', PACKAGE = 'GWmodel', y, X, beta)
}

rss <- function(y, X, beta) {
    .Call('GWmodel_rss', PACKAGE = 'GWmodel', y, X, beta)
}

gwr_diag <- function(y,x, beta, S) {
    .Call('GWmodel_gwr_diag', PACKAGE = 'GWmodel', y, x, beta, S)
}

gwr_diag1 <- function(y,x, beta, s_hat) {
  .Call('GWmodel_gwr_diag1', PACKAGE = 'GWmodel', y, x, beta, s_hat)
}

AICc <- function(y,x, beta, S) {
    .Call('GWmodel_AICc', PACKAGE = 'GWmodel', y,x, beta, S)
}

AICc1 <- function(y,x, beta, s_hat) {
  .Call('GWmodel_AICc1', PACKAGE = 'GWmodel', y,x, beta, s_hat)
}

AICc_rss <- function(y,x, beta, S) {
    .Call('GWmodel_AICc_rss', PACKAGE = 'GWmodel', y,x, beta, S)
}

AICc_rss1 <- function(y,x, beta, s_hat) {
  .Call('GWmodel_AICc_rss1', PACKAGE = 'GWmodel', y,x, beta, s_hat)
}

Ci_mat <- function(x, w) {
    .Call('GWmodel_Ci_mat', PACKAGE = 'GWmodel', x, w)
}

#scgwr_pre(mat x, vec y, int bw, int poly, double b0, mat g0, mat neighbour)
scgwr_pre <- function(x, y, bw, poly, b0, g0, neighbour) {
    .Call('GWmodel_scgwr_pre', PACKAGE = 'GWmodel', x, y, bw, poly, b0, g0, neighbour)
}

#scgwr_reg(mat x, vec y, int bw, int poly, mat G0, mat Mx0, mat My0, mat XtX, mat XtY, mat neighbour, vec parameters);
scgwr_reg <- function(x, y, bw, poly, G0, Mx0, My0, XtX, XtY, neighbour, parameters) {
    .Call('GWmodel_scgwr_reg', PACKAGE = 'GWmodel', x, y, bw, poly, G0, Mx0, My0, XtX, XtY, neighbour, parameters)
}

#scgwr_loocv(vec target, mat x, vec y, int bw, int poly, mat Mx0, mat My0, mat XtX, mat XtY)
scgwr_loocv <- function(target, x, y, bw, poly, Mx0, My0, XtX, XtY) {
    .Call('GWmodel_scgwr_loocv', PACKAGE = 'GWmodel', target, x, y, bw, poly, Mx0, My0, XtX, XtY)
}

gw_dist <- function(dp.locat, rp.locat, focus, p, theta, longlat, rp.given) {
  .Call('GWmodel_gw_dist', PACKAGE = 'GWmodel', dp.locat, rp.locat, focus, p, theta, longlat, rp.given)
}

gw_reg_all <- function(x, y, dp.locat, rp.given, rp.locat, dm.given, dmat, hatmatrix, p, theta, longlat, bw, kernel, adaptive, ngroup = 1, igroup = 1) {
  kernel.id <- switch (kernel,
                       gaussian = 0,
                       exponential = 1,
                       bisquare = 2,
                       tricube  = 3,
                       boxcar   = 4)
  .Call('GWmodel_gw_reg_all', PACKAGE = 'GWmodel', 
        x, y, dp.locat, rp.given, rp.locat, dm.given, dmat, hatmatrix, p, theta, longlat, bw, kernel.id, adaptive, ngroup, igroup - 1)
}

gw_reg_all_omp <- function(x, y, dp.locat, rp.given, rp.locat, dm.given, dmat, hatmatrix, p, theta, longlat, bw, kernel, adaptive, threads = 0, ngroup = 1, igroup = 1) {
  kernel.id <- switch (kernel,
                       gaussian = 0,
                       exponential = 1,
                       bisquare = 2,
                       tricube  = 3,
                       boxcar   = 4)
  .Call('GWmodel_gw_reg_all_omp', PACKAGE = 'GWmodel', 
        x, y, dp.locat, rp.given, rp.locat, dm.given, dmat, hatmatrix, p, theta, longlat, bw, kernel.id, adaptive, threads, ngroup, igroup - 1)
}

gw_reg_all_cuda <- function(x, y, dp.locat, rp.given, rp.locat, dm.given, dmat, hatmatrix, p, theta, longlat, bw, kernel, adaptive, groupl = 0, gpuID = 1) {
  kernel.id <- switch (kernel,
                       gaussian = 0,
                       exponential = 1,
                       bisquare = 2,
                       tricube  = 3,
                       boxcar   = 4)
  .Call('GWmodel_gw_reg_cuda', PACKAGE = 'GWmodel', 
        x, y, dp.locat, rp.given, rp.locat, dm.given, dmat, hatmatrix, p, theta, longlat, bw, kernel.id, adaptive, groupl, gpuID - 1)
}

gw_cv_all <- function(x, y, dp.locat, dm.given, dmat, p, theta, longlat, bw, kernel, adaptive, ngroup = 1, igroup = 1) {
  kernel.id <- switch (kernel,
                       gaussian = 0,
                       exponential = 1,
                       bisquare = 2,
                       tricube  = 3,
                       boxcar   = 4)
  .Call('GWmodel_gw_cv_all', PACKAGE = 'GWmodel', 
        x, y, dp.locat, dm.given, dmat, p, theta, longlat, bw, kernel.id, adaptive, ngroup, igroup - 1)
}

gw_cv_all_omp <- function(x, y, dp.locat, dm.given, dmat, p, theta, longlat, bw, kernel, adaptive, threads = 0, ngroup = 1, igroup = 1) {
  kernel.id <- switch (kernel,
                       gaussian = 0,
                       exponential = 1,
                       bisquare = 2,
                       tricube  = 3,
                       boxcar   = 4)
  .Call('GWmodel_gw_cv_all_omp', PACKAGE = 'GWmodel', 
        x, y, dp.locat, dm.given, dmat, p, theta, longlat, bw, kernel.id, adaptive, threads, ngroup, igroup - 1)
}

gw_cv_all_cuda <- function(x, y, dp.locat, dm.given, dmat, p, theta, longlat, bw, kernel, adaptive, groupl = 0, gpuID = 1) {
  kernel.id <- switch (kernel,
                       gaussian = 0,
                       exponential = 1,
                       bisquare = 2,
                       tricube  = 3,
                       boxcar   = 4)
  .Call('GWmodel_gw_cv_all_cuda', PACKAGE = 'GWmodel', 
        x, y, dp.locat, dm.given, dmat, p, theta, longlat, bw, kernel.id, adaptive, groupl, gpuID - 1)
}

gw_local_r2 <- function(dp, dybar2, dyhat2, dm_given, dmat, p, theta, longlat, bw, kernel, adaptive) {
  kernel.id <- switch (kernel,
                       gaussian = 0,
                       exponential = 1,
                       bisquare = 2,
                       tricube  = 3,
                       boxcar   = 4)
  .Call('GWmodel_gw_local_r2', PACKAGE = 'GWmodel', dp, dybar2, dyhat2, dm_given, dmat, p, theta, longlat, bw, kernel.id, adaptive)
}

gwr_q <- function(x,  y, dMat, bw, kernel, adaptive) 
{
   .Call('GWmodel_gwr_q', PACKAGE = 'GWmodel', x,  y, dMat, bw, kernel, adaptive)  
}
gwr_mixed_trace <- function(x1, x2, y, dMat, bw, kernel, adaptive) 
{
   .Call('GWmodel_gwr_mixed_trace', PACKAGE = 'GWmodel', x1, x2, y, dMat, bw, kernel, adaptive) 
}
gwr_mixed_2 <- function(x1, x2, y, dMat, dMat.rp, bw, kernel, adaptive) 
{
   .Call('GWmodel_gwr_mixed_2', PACKAGE = 'GWmodel', x1, x2, y, dMat, dMat.rp, bw, kernel, adaptive)  
}