// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393
// [[Rcpp::depends(RcppArmadillo)]]
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;
using namespace arma;

// GWmodel_oordinate_rotate
arma::mat coordinate_rotate(arma::mat coords, double theta);
RcppExport SEXP GWmodel_coordinate_rotate(SEXP coordsSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type coords(coordsSEXP);
	Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    __result = Rcpp::wrap(coordinate_rotate(coords, theta));
    return __result;
END_RCPP
}

// GWmodel_eu_dist_vec
arma::vec eu_dist_vec(arma::mat in_locs, arma::vec out_loc);
RcppExport SEXP GWmodel_eu_dist_vec(SEXP in_locsSEXP, SEXP out_locSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
	Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type in_locs(in_locsSEXP);
	Rcpp::traits::input_parameter< arma::vec >::type out_loc(out_locSEXP);
    __result = Rcpp::wrap(eu_dist_vec(in_locs, out_loc));
    return __result;
END_RCPP
}

// GWmodel_eu_dist_mat
arma::mat eu_dist_mat(arma::mat in_locs, arma::mat out_locs);
RcppExport SEXP GWmodel_eu_dist_mat(SEXP in_locsSEXP, SEXP out_locsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
	Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type in_locs(in_locsSEXP);
	Rcpp::traits::input_parameter< arma::mat >::type out_locs(out_locsSEXP);
    __result = Rcpp::wrap(eu_dist_mat(in_locs, out_locs));
    return __result;
END_RCPP
}

// GWmodel_eu_dist_smat
arma::mat eu_dist_smat(arma::mat in_locs);
RcppExport SEXP GWmodel_eu_dist_smat(SEXP in_locsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
	Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type in_locs(in_locsSEXP);
    __result = Rcpp::wrap(eu_dist_smat(in_locs));
    return __result;
END_RCPP
}

// GWmodel_md_dist_vec
arma::vec md_dist_vec(mat in_locs, vec out_loc);
RcppExport SEXP GWmodel_md_dist_vec(SEXP in_locsSEXP, SEXP out_locSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
	Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type in_locs(in_locsSEXP);
	Rcpp::traits::input_parameter< arma::vec >::type out_loc(out_locSEXP);
    __result = Rcpp::wrap(md_dist_vec(in_locs, out_loc));
    return __result;
END_RCPP
}

// GWmodel_md_dist_mat
arma::mat md_dist_mat(arma::mat in_locs, arma::mat out_locs);
RcppExport SEXP GWmodel_md_dist_mat(SEXP in_locsSEXP, SEXP out_locsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
	Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type in_locs(in_locsSEXP);
	Rcpp::traits::input_parameter< arma::mat >::type out_locs(out_locsSEXP);
    __result = Rcpp::wrap(md_dist_mat(in_locs, out_locs));
    return __result;
END_RCPP
}

// GWmodel_md_dist_smat
arma::mat md_dist_smat(arma::mat in_locs);
RcppExport SEXP GWmodel_md_dist_smat(SEXP in_locsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
	Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type in_locs(in_locsSEXP);
    __result = Rcpp::wrap(md_dist_smat(in_locs));
    return __result;
END_RCPP
}

// GWmodel_cd_dist_vec
arma::vec cd_dist_vec(arma::mat in_locs, arma::vec out_loc);
RcppExport SEXP GWmodel_cd_dist_vec(SEXP in_locsSEXP, SEXP out_locSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
	Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type in_locs(in_locsSEXP);
	Rcpp::traits::input_parameter< arma::vec >::type out_loc(out_locSEXP);
    __result = Rcpp::wrap(cd_dist_vec(in_locs, out_loc));
    return __result;
END_RCPP
}

// GWmodel_cd_dist_mat
arma::mat cd_dist_mat(arma::mat in_locs, arma::mat out_locs);
RcppExport SEXP GWmodel_cd_dist_mat(SEXP in_locsSEXP, SEXP out_locsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
	Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type in_locs(in_locsSEXP);
	Rcpp::traits::input_parameter< arma::mat >::type out_locs(out_locsSEXP);
    __result = Rcpp::wrap(cd_dist_mat(in_locs, out_locs));
    return __result;
END_RCPP
}

// GWmodel_cd_dist_smat
arma::mat cd_dist_smat(arma::mat in_locs);
RcppExport SEXP GWmodel_cd_dist_smat(SEXP in_locsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
	Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type in_locs(in_locsSEXP);
    __result = Rcpp::wrap(cd_dist_smat(in_locs));
    return __result;
END_RCPP
}

// GWmodel_mk_dist_vec
arma::vec mk_dist_vec(arma::mat in_locs, arma::vec out_loc, double p);
RcppExport SEXP GWmodel_mk_dist_vec(SEXP in_locsSEXP, SEXP out_locSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
	Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type in_locs(in_locsSEXP);
	Rcpp::traits::input_parameter< arma::vec >::type out_loc(out_locSEXP);
	Rcpp::traits::input_parameter< double >::type p(pSEXP);
    __result = Rcpp::wrap(mk_dist_vec(in_locs, out_loc, p));
    return __result;
END_RCPP
}

// GWmodel_mk_dist_mat
arma::mat mk_dist_mat(arma::mat in_locs, arma::mat out_locs,double p);
RcppExport SEXP GWmodel_mk_dist_mat(SEXP in_locsSEXP, SEXP out_locsSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
	Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type in_locs(in_locsSEXP);
	Rcpp::traits::input_parameter< arma::mat >::type out_locs(out_locsSEXP);
	Rcpp::traits::input_parameter< double >::type p(pSEXP);
    __result = Rcpp::wrap(mk_dist_mat(in_locs, out_locs, p));
    return __result;
END_RCPP
}

// GWmodel_mk_dist_smat
arma::mat mk_dist_smat(arma::mat in_locs,double p);
RcppExport SEXP GWmodel_mk_dist_smat(SEXP in_locsSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
	Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type in_locs(in_locsSEXP);
	Rcpp::traits::input_parameter< double >::type p(pSEXP);
    __result = Rcpp::wrap(mk_dist_smat(in_locs, p));
    return __result;
END_RCPP
}

// GWmodel_bisq_wt_vec
arma::vec bisq_wt_vec(arma::vec distv, double bw);
RcppExport SEXP GWmodel_bisq_wt_vec(SEXP distvSEXP, SEXP bwSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
	Rcpp::RNGScope __rngScope;
	Rcpp::traits::input_parameter< arma::vec >::type distv(distvSEXP);
	Rcpp::traits::input_parameter< double >::type bw(bwSEXP);
    __result = Rcpp::wrap(bisq_wt_vec(distv, bw));
    return __result;
END_RCPP
}

// GWmodel_bisq_wt_mat
arma::mat bisq_wt_mat(arma::mat distm, arma::vec bw);
RcppExport SEXP GWmodel_bisq_wt_mat(SEXP distmSEXP, SEXP bwSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
	Rcpp::RNGScope __rngScope;
	Rcpp::traits::input_parameter< arma::mat >::type distm(distmSEXP);
	Rcpp::traits::input_parameter< arma::vec >::type bw(bwSEXP);
    __result = Rcpp::wrap(bisq_wt_mat(distm, bw));
    return __result;
END_RCPP
}

// GWmodel_gauss_wt_vec
arma::vec gauss_wt_vec(arma::vec distv, double bw);
RcppExport SEXP GWmodel_gauss_wt_vec(SEXP distvSEXP, SEXP bwSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
	Rcpp::RNGScope __rngScope;
	Rcpp::traits::input_parameter< arma::vec >::type distv(distvSEXP);
	Rcpp::traits::input_parameter< double >::type bw(bwSEXP);
    __result = Rcpp::wrap(gauss_wt_vec(distv, bw));
    return __result;
END_RCPP
}

// GWmodel_gauss_wt_mat
arma::mat gauss_wt_mat(arma::mat distm, arma::vec bw);
RcppExport SEXP GWmodel_gauss_wt_mat(SEXP distmSEXP, SEXP bwSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
	Rcpp::RNGScope __rngScope;
	Rcpp::traits::input_parameter< arma::mat >::type distm(distmSEXP);
	Rcpp::traits::input_parameter< arma::vec >::type bw(bwSEXP);
    __result = Rcpp::wrap(gauss_wt_mat(distm, bw));
    return __result;
END_RCPP
}

// GWmodel_tri_wt_vec
arma::vec tri_wt_vec(arma::vec distv, double bw);
RcppExport SEXP GWmodel_tri_wt_vec(SEXP distvSEXP, SEXP bwSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
	Rcpp::RNGScope __rngScope;
	Rcpp::traits::input_parameter< arma::vec >::type distv(distvSEXP);
	Rcpp::traits::input_parameter< double >::type bw(bwSEXP);
    __result = Rcpp::wrap(tri_wt_vec(distv, bw));
    return __result;
END_RCPP
}

// GWmodel_tri_wt_mat
arma::mat tri_wt_mat(arma::mat distm, arma::vec bw);
RcppExport SEXP GWmodel_tri_wt_mat(SEXP distmSEXP, SEXP bwSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
	Rcpp::RNGScope __rngScope;
	Rcpp::traits::input_parameter< arma::mat >::type distm(distmSEXP);
	Rcpp::traits::input_parameter< arma::vec >::type bw(bwSEXP);
    __result = Rcpp::wrap(tri_wt_mat(distm, bw));
    return __result;
END_RCPP
}

// GWmodel_exp_wt_vec
arma::vec exp_wt_vec(arma::vec distv, double bw);
RcppExport SEXP GWmodel_exp_wt_vec(SEXP distvSEXP, SEXP bwSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
	Rcpp::RNGScope __rngScope;
	Rcpp::traits::input_parameter< arma::vec >::type distv(distvSEXP);
	Rcpp::traits::input_parameter< double >::type bw(bwSEXP);
    __result = Rcpp::wrap(exp_wt_vec(distv, bw));
    return __result;
END_RCPP
}

// GWmodel_exp_wt_mat
arma::mat exp_wt_mat(arma::mat distm, arma::vec bw);
RcppExport SEXP GWmodel_exp_wt_mat(SEXP distmSEXP, SEXP bwSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
	Rcpp::RNGScope __rngScope;
	Rcpp::traits::input_parameter< arma::mat >::type distm(distmSEXP);
	Rcpp::traits::input_parameter< arma::vec >::type bw(bwSEXP);
    __result = Rcpp::wrap(exp_wt_mat(distm, bw));
    return __result;
END_RCPP
}

//GWmodel_gw_reg
Rcpp::List gw_reg(mat x, vec y, vec w, bool hatmatrix, int focus);
RcppExport SEXP GWmodel_gw_reg(SEXP xSEXP, SEXP ySEXP, SEXP wSEXP, SEXP hatmatrixSEXP,SEXP focusSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
	Rcpp::RNGScope __rngScope;
	Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
	Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
	Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
	Rcpp::traits::input_parameter< bool >::type hatmatrix(hatmatrixSEXP);
	Rcpp::traits::input_parameter< int >::type focus(focusSEXP);
    __result = Rcpp::wrap(gw_reg(x, y, w, hatmatrix, focus));
    return __result;
END_RCPP
}

//GWmodel_fitted
arma::vec fitted(arma::mat X, arma::mat beta);
RcppExport SEXP GWmodel_fitted(SEXP XSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
	Rcpp::RNGScope __rngScope;
	Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
	Rcpp::traits::input_parameter< arma::mat >::type beta(betaSEXP);
    __result = Rcpp::wrap(fitted(X, beta));
    return __result;
END_RCPP
}

//GWmodel_ehat
arma::vec ehat(arma::vec y, arma::mat X, arma::mat beta);
RcppExport SEXP GWmodel_ehat(SEXP ySEXP, SEXP XSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
	Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
	Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
	Rcpp::traits::input_parameter< arma::mat >::type beta(betaSEXP);
    __result = Rcpp::wrap(ehat(y, X, beta));
    return __result;
END_RCPP
}
//GWmodel_rss
arma::vec rss(arma::vec y, arma::mat X, arma::mat beta);
RcppExport SEXP GWmodel_rss(SEXP ySEXP, SEXP XSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
	Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
	Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
	Rcpp::traits::input_parameter< arma::mat >::type beta(betaSEXP);
    __result = Rcpp::wrap(rss(y, X, beta));
    return __result;
END_RCPP
}

//GWmodel_gwr_diag
arma::vec gwr_diag(arma::vec y,arma::mat x, arma::mat beta, arma::mat S);
RcppExport SEXP GWmodel_gwr_diag(SEXP ySEXP, SEXP xSEXP, SEXP betaSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
	Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
	Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
	Rcpp::traits::input_parameter< arma::mat >::type beta(betaSEXP);
	Rcpp::traits::input_parameter< arma::mat >::type S(SSEXP);
    __result = Rcpp::wrap(gwr_diag(y, x, beta, S));
    return __result;
END_RCPP
}

//GWmodel_AICc
double AICc(arma::vec y,arma::mat x, arma::mat beta, arma::mat S);
RcppExport SEXP GWmodel_AICc(SEXP ySEXP, SEXP xSEXP, SEXP betaSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
	Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
	Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
	Rcpp::traits::input_parameter< arma::mat >::type beta(betaSEXP);
	Rcpp::traits::input_parameter< arma::mat >::type S(SSEXP);
    __result = Rcpp::wrap(AICc(y, x, beta, S));
    return __result;
END_RCPP
}

//GWmodel_AICc_rss
arma::vec AICc_rss(arma::vec y,arma::mat x, arma::mat beta, arma::mat S);
RcppExport SEXP GWmodel_AICc_rss(SEXP ySEXP, SEXP xSEXP, SEXP betaSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
	Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
	Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
	Rcpp::traits::input_parameter< arma::mat >::type beta(betaSEXP);
	Rcpp::traits::input_parameter< arma::mat >::type S(SSEXP);
    __result = Rcpp::wrap(AICc_rss(y, x, beta, S));
    return __result;
END_RCPP
}

//GWmodel_Ci_mat
arma::mat Ci_mat(arma::mat x, arma::vec w);
RcppExport SEXP GWmodel_Ci_mat(SEXP xSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
	Rcpp::RNGScope __rngScope;
	Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
	Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    __result = Rcpp::wrap(Ci_mat(x,w));
    return __result;
END_RCPP
}